name: Version bump

on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Bump version
              uses: remorses/bump-version@js
              with:
                  version_file: ./VERSION
                  prefix: v
                  github_token: ${{ secrets.GITHUB_TOKEN }}
