name: Release Drafter

on:
    push:
        branches:
            - master
        paths-ignore:
            - "VERSION"
            - "README.md"

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v2

            - name: Bump Version
              uses: remorses/bump-version@js
              with:
                  version_file: VERSION
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    draft:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v2

            - name: Release Drafter
              id: release_drafter
              uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Display structure of downloaded files
              run: ls -R
              working-directory: path/to/artifact

            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: MalFramework_${{ github.sha }}.zip

            - name: Upload release asset
              uses: actions/upload-release-asset@v1.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.release_drafter.outputs.upload_url }}
                  asset_path: ./MalFramework_${{ github.sha }}.zip
                  asset_name: MalFramework_${{ github.sha }}.zip
                  asset_content_type: application/zip
