name: Release Drafter

on:
    push:
        branches:
            - master

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - name: Bump Version
              uses: remorses/bump-version@js
              with:
                  version_file: ./VERSION
                  prefix: v
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    draft:
        runs-on: ubuntu-latest
        steps:
            - name: Release Drafter
              uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
